### ISSUE TITLE
512MB quota exceeded?

### ISSUE THREAD

**Issue by subpl** [vasanthv/jsonbox#22]
A 512MB quota is very reasonable for this service.

When I POST to my box, I receive this:

```bash
> curl -X POST "https://jsonbox.io/box_cb9c0a7cb8c971182f81" -H 'content-type: application/json' -d '{"id": 0, "text": "do-me", "assigned": false, "done": false}'
{"message":"you are over your space quota, using 516 MB of 512 MB"}
```

My box is at https://jsonbox.io/box_cb9c0a7cb8c971182f81 (it's not sensitive content to me). Its size:

```bash
> curl https://jsonbox.io/box_cb9c0a7cb8c971182f81 | wc --bytes
1444
```

1.4MB, not 516MB.

This is a great service, and I like it. This issue isn't holding anything up, just curious why this is happening. Poked around a bit and couldn't see anything obvious.

**Comment by subpl** [comment]
This looks like `jsonbox`'s exceeding their MongoDB Atlas M0 free-tier account quota, and not my box exceeding its `jsonbox` quota.

I no longer consider this a bug with `jsonbox`, but a notification to @vasanthv that he has exceeded his free tier on Atlas.

**Comment by fankay** [comment]
Yes, I have the same problem @vasanthv

**Comment by vasanthv** [comment]
Thanks for reporting. Upgraded the cluster now.

**Comment by paulocoghi** [comment]
_Disclaimer: I do not work for OVH or any related company._

Since there is no compromise with high availability of the data, instead of using a MongoDB Atlas Cluster tied with a cloud provider that charges for everything including traffic, why not use a cheap dedicated server like the ones offered on https://www.kimsufi.com/us/en/servers.xml

For example, [the KS-9 Xeon server on the list](https://www.kimsufi.com/us/en/servers.xml) costs $20/month and has 16GB of RAM, two SSD of 240GB in RAID and unmetered 100Mbps network.

If SSD performance isn't a requirement, the KS-11 is identical, with the exception of the disk, that is a 2x2TB RAID.

If more RAM is needed, the KS-12 offer the same Xeon with 32GB of RAM for $29/month.

When even more resources are needed, including network speed, on [SoYouStart](https://www.soyoustart.com/us/essential-servers/) there are servers from 32GB to 128GB of RAM with unmetered 250Mbps network and many options for disk RAID's, both SSD and SATA.

---

I am available to configure the dedicated server of your choice with MongoDB, if you understand that this solution is viable.
